services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile_dev
    container_name: go
    environment:
      Port: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
        - "1883:1883"
        - "9001:9001"
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf    
    restart: always

    