FROM golang:1.22.4

RUN mkdir /app

WORKDIR /app

ADD . /app

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

RUN go mod download

ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
