services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile_dev
    container_name: go
    environment:
      Port: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    networks:
      - goland-network
    depends_on:
      mysql:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto
    ports:
        - "1883:1883"
        - "9001:9001"
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf    
    restart: always
    networks:
      - goland-network

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 2s
      retries: 3
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
      - goland-network

  adminer:
    container_name: adminer
    depends_on:
      - mysql
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks:
      - goland-network


networks:
  goland-network:
    driver: bridge
    